const fs=require('node:fs'),assert=require('node:assert/strict');const path=require('node:path');const {chromium}=require('playwright');process.chdir(path.resolve(__dirname,'..'));fs.mkdirSync('.qa',{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,...(process.env.RDG_BROWSER_CHANNEL?{channel:process.env.RDG_BROWSER_CHANNEL}:{})}),c=await b.newContext(),p=await c.newPage();await c.route('**/js/config.js*',r=>r.fulfill({contentType:'application/javascript',body:fs.readFileSync('js/config.js','utf8').replace(/firebase: \{[\s\S]*?\n  \},/,'firebase: {},').replace('demo: false','demo: true')}));await p.goto('http://127.0.0.1:4173/');await p.waitForSelector('.product');await p.evaluate(()=>document.fonts.ready);
for(const width of [320,390,768,1024,1440]){await p.setViewportSize({width,height:900});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))console.log(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(el=>el.getBoundingClientRect().right>innerWidth+1&&!el.closest('.categories')).map(el=>({tag:el.tagName,cls:el.className,right:el.getBoundingClientRect().right,width:el.getBoundingClientRect().width})).slice(0,15)})));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Overflow '+width);await p.getByRole('button',{name:'Escolher Patinho Angus',exact:true}).click();assert.equal(await p.locator('.variant-choice').count(),4);assert.equal(await p.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth>d.clientWidth}),false,'Dialog overflow '+width);await p.getByRole('button',{name:'Fechar',exact:true}).click();console.log('PASS layout',width)}
await p.setViewportSize({width:320,height:844});
await p.getByRole('button',{name:'Escolher Patinho Angus',exact:true}).click();
assert.match(await p.locator('#product-quantity').innerText(),/0,500 kg \(500 g\)/);
await p.locator('[name=amount]').fill('1.300');
assert.match(await p.locator('#product-quantity').innerText(),/1,300 kg/);
assert.equal(await p.locator('[name=amount]').evaluate(el=>el.validity.valid),true);
await p.getByRole('button',{name:'Adicionar à sacola',exact:true}).click();
await p.locator('.mobile-cart').click();
assert.equal(await p.locator('#modal-cart .quantity-value').innerText(),'1,300 kg');
assert.equal(await p.locator('dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);
await p.screenshot({path:'.qa/quantities-cart-320.png'});
await p.locator('#modal-cart [data-remove]').click();
await p.getByRole('button',{name:'Fechar',exact:true}).click();
await p.setViewportSize({width:390,height:844});await p.getByRole('button',{name:'Escolher Picanha Estância 92',exact:true}).click();await p.locator('[name=amount]').fill('2');assert.match(await p.locator('#product-total').innerText(),/357,60/);assert.match(await p.locator('#product-quantity').innerText(),/Quantidade: 2 peças.*2,400 kg/);await p.getByRole('button',{name:'Adicionar à sacola',exact:true}).click();await p.locator('.mobile-cart').click();await p.locator('#modal-cart [data-delta="1"]').click();assert.match(await p.locator('#modal-cart .stepper').innerText(),/3 peças/);await p.locator('#modal-cart [data-remove]').click();assert.equal(await p.locator('#modal-cart .cart-line').count(),0);await p.getByRole('button',{name:'Fechar',exact:true}).click();
// A local fixture with differing store price and missing stock tests the last-step buttons.
const seed=JSON.parse(fs.readFileSync('data/catalog.json'));
await p.evaluate(seed=>{const b=structuredClone(seed),c=structuredClone(seed);b.products.find(p=>p.id==='1502178').variants[0].priceCents=7000;c.products.find(p=>p.id==='1502178').active=false;localStorage.setItem('rdg-demo-v1:catalog:bingen',JSON.stringify(b));localStorage.setItem('rdg-demo-v1:catalog:correas',JSON.stringify(c));},seed);
await p.reload();await p.waitForSelector('.product');await p.getByRole('button',{name:'Escolher Patinho Angus',exact:true}).click();await p.getByRole('button',{name:'Adicionar à sacola',exact:true}).click();await p.locator('.mobile-cart').click();await p.locator('#modal-cart [data-action=checkout]').click();await p.locator('[name=name]').fill('Teste de preço');await p.locator('[name=phone]').fill('123');await p.getByRole('button',{name:'Enviar pedido',exact:true}).click();assert.match(await p.locator('#checkout-error').innerText(),/telefone válido/);assert.equal(await p.locator('[data-branch]').count(),0);await p.locator('[name=phone]').fill('24999990001');await p.getByRole('button',{name:'Enviar pedido',exact:true}).click();await p.waitForSelector('[data-branch]');assert.match(await p.locator('[data-branch=coronel]').innerText(),/32,95/);assert.match(await p.locator('[data-branch=bingen]').innerText(),/35,00/);assert.equal(await p.locator('[data-branch=correas]').isDisabled(),true);const heading=await p.locator('#modal-title').boundingBox(),dialog=await p.locator('#modal').boundingBox();assert.ok(heading.y>=dialog.y+10);await p.screenshot({path:'.qa/revised-store-availability.png'});console.log('PASS whole-piece weight, quantity +/- and remove; invalid phone; real store totals; unavailable-store button; dialog title visible.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
